### ISSUE TITLE
Clean up code in firebase.js and List.jsx

### ISSUE THREAD

**Issue by Trevor-Rezac** [the-collab-lab/tcl-45-smart-shopping-list#43]
Currently there is a lot of unused code and logic in `firebase.js`. Everything below line 129 is not currently being used and can be removed.

Also, the `filteredGroups` reduce function in List.jsx on line 72 is not currently in use. This can be removed as well. 

Assigning myself and Mira to this issue since she and I were the ones who initially added these unused code blocks.

**Comment by N-Zubko** [comment]
So you think we could implement this in List.jsx [Issue #42 ](https://github.com/the-collab-lab/tcl-45-smart-shopping-list/issues/42) ?

**Comment by Trevor-Rezac** [comment]
Hey Nadia, can you clarify your question a little? I'm not quite sure I understand. Implement what exactly? My intention with this issue was mostly code clean up, not implementing anything new.

**Comment by N-Zubko** [comment]
@Trevor-Rezac no worries, I talked to Lindsey yesterday and she explained one more time how the whole code works and whatever I was going to suggest does not fit in your solution
