### ISSUE TITLE
Allow users to edit an item already added to the list

### ISSUE THREAD

**Issue by Trevor-Rezac** [the-collab-lab/tcl-45-smart-shopping-list#51]
Adding an 'edit' button with each item would allow the user to update or change the text content of the item, without having to delete the item. Deleting the item would reset any of the established purchase history/behavior and the user may not want to do that, they may only want to make a minor change to the name of the item, like a misspelling, capitalization, etc.

**Comment by N-Zubko** [comment]
And we need an edit button next to Delete

**Comment by Trevor-Rezac** [comment]
Yep I agree! I think it should be a fairly easy implementation because most of the logic is already there.
